n_iters: 20000
lr_sg_lobe_axis: 0.001
lr_sg_sharpness: 0.001
lr_sg_amplitude: 0.001
lr_asg_rotation: 0.001
lr_asg_scale: 0.001
lr_asg_amplitude: 0.001
lr_sigma_mlp: 0.001
lr_k_coeffs: 0.0001
lr_scheduler_step: 5000
lr_scheduler_gamma: 0.9
batch_size: 1024
patch_based_sampling: false
log_every_n: 50
log_grads: false
log_sigma: false
eval_every_n: 5000
adapt_control_from_iter: 500
adapt_control_every_iter: 500
adapt_control_to_iter: 15000
reg_laplacian: 0.0
reg_lstsq_1: 0.1
reg_lstsq_2: 0.1
